# -*- mode: python ; coding: utf-8 -*-


a = Analysis(
    ['cgc/cli/main.py'],
    pathex=[],
    binaries=[],
    datas=[],
    hiddenimports=[
        'cgc',
        'cgc.cli',
        'cgc.cli.main',
        'cgc.core',
        'cgc.core.schema',
        'cgc.core.query',
        'cgc.core.chunk',
        'cgc.core.graph',
        'cgc.core.triplet',
        'cgc.core.errors',
        'cgc.connector',
        'cgc.session',
        'cgc.adapters',
        'cgc.adapters.base',
        'cgc.adapters.sql',
        'cgc.adapters.filesystem',
        # Graph adapters (v0.4.0)
        'cgc.adapters.graph',
        'cgc.adapters.graph.base',
        'cgc.adapters.graph.neo4j',
        'cgc.adapters.graph.age',
        # Discovery modules (v0.2.0)
        'cgc.discovery',
        'cgc.discovery.engine',
        'cgc.discovery.patterns',
        'cgc.discovery.filters',
        'cgc.discovery.constraints',
        'cgc.discovery.industry_packs',
        'cgc.discovery.extractor',
        'cgc.discovery.structured',
        'cgc.discovery.gliner',
        'cgc.discovery.glirel',
        'cgc.discovery.unified',
        'cgc.discovery.router',
        # Licensing (v0.3.0)
        'cgc.licensing',
        'cgc.licensing.store',
        'cgc.licensing.tier',
        'cgc.licensing.validator',
    ],
    hookspath=['hooks'],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='cgc',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
