# -*- mode: python ; coding: utf-8 -*-


a = Analysis(
    ['cgc/mcp/__main__.py'],
    pathex=[],
    binaries=[],
    datas=[],
    hiddenimports=[
        'cgc',
        'cgc.mcp',
        'cgc.mcp.server',
        'cgc.core',
        'cgc.core.schema',
        'cgc.core.query',
        'cgc.core.chunk',
        'cgc.core.graph',
        'cgc.core.triplet',
        'cgc.core.errors',
        'cgc.connector',
        'cgc.session',
        'cgc.adapters',
        'cgc.adapters.base',
        'cgc.adapters.sql',
        'cgc.adapters.filesystem',
        # Discovery modules (v0.2.0) — pattern-only extraction
        'cgc.discovery',
        'cgc.discovery.engine',
        'cgc.discovery.patterns',
        'cgc.discovery.filters',
        'cgc.discovery.constraints',
        'cgc.discovery.industry_packs',
        'cgc.discovery.extractor',
        'cgc.discovery.structured',
        # NOTE: gliner, glirel, unified, router are lazy-loaded
        # and excluded below (they pull in torch/spacy/transformers)
    ],
    hookspath=['hooks'],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        'torch',
        'spacy',
        'gliner',
        'glirel',
        'scipy',
        'sklearn',
        'transformers',
        'sentence_transformers',
        'thinc',
    ],
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='cgc_mcp',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
